Description: Create a S3 bucket with a public access policy

Resources:
  PetBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
  
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PetBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${PetBucket.Arn}/*"

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref PetBucket
