Description: ALB Alias Record

Parameters:
  EnvId:
    Type: String
    Default: project
  
  HostedZoneId:
    Type: String
    Description: "The ID of the existing Route 53 Hosted Zone"
  
  DomainName:
    Type: String
    Description: "The domain name for the ALB"

Resources:
  ALBAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${EnvId}.${DomainName}"
      Type: A
      AliasTarget:
        DNSName:
          Fn::ImportValue: !Sub "${EnvId}-ALBDNSName"
        HostedZoneId: 
          Fn::ImportValue: !Sub "${EnvId}-ALBZoneId"
        EvaluateTargetHealth: false

Outputs:
  ALBAliasRecordName:
    Description: Name of the ALB Alias Record
    Value: !Ref ALBAliasRecord
    Export:
      Name: !Sub "${EnvId}-ALBAliasRecordName"