Description: Petoboto API Domain Mapping

Parameters:
  EnvId:
    Type: String
    Default: project
    Description: Environment identifier used for cross-stack imports.
    
  Color:
    Type: String
    Default: blue
    Description: Color identifier used to suffix cross-stack imports and exports.

  DomainName:
    Type: String
    Description: API domain name (e.g. api.example.com)

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID containing the domain

Resources:
  ApiDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Sub "${EnvId}-${Color}-api.${DomainName}"
      DomainNameConfigurations:
        - CertificateArn:
            Fn::ImportValue: !Sub "${EnvId}-AcmCertificateArn"
          EndpointType: REGIONAL

  ApiDomainMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${EnvId}-${Color}-PetobotoApiId"
      DomainName: !Ref ApiDomain
      Stage: "$default"
    DependsOn: ApiDomain

  ApiDomainARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${EnvId}-${Color}-api.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiDomain.RegionalDomainName
        HostedZoneId: !GetAtt ApiDomain.RegionalHostedZoneId

Outputs:
  ApiDomain:
    Description: API domain name
    Value: !Ref DomainName
    Export:
      Name: !Sub "${EnvId}-${Color}-ApiDomain"

  ApiDomainUrl:
    Description: Base URL using API domain
    Value: !Sub "https://${EnvId}-api.${DomainName}/"
    Export:
      Name: !Sub "${EnvId}-${Color}-ApiDomainUrl"