
AWSTemplateFormatVersion: 2010-09-09
Description: Route 53 HTTPS health check for the API path /api/_hc via CloudFront/custom domain

Parameters:
  EnvId:
    Type: String
    Default: project
    Description: Environment identifier used to compose the FQDN and export names.

  DomainName:
    Type: String
    Description: The apex/root domain (e.g., example.com) used with the EnvId subdomain.

  HealthCheckPath:
    Type: String
    Default: /api/_hc
    Description: The HTTP(S) resource path to check.

  HealthCheckPort:
    Type: Number
    Default: 443
    AllowedValues: [80, 443]
    Description: Port for the health check.

  RequestInterval:
    Type: Number
    Default: 30
    AllowedValues: [10, 30]
    Description: Interval in seconds between health checks. 10s has higher cost.

  FailureThreshold:
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 10
    Description: Number of consecutive health check failures before considering unhealthy.

Resources:
  ApiHttpsHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        FullyQualifiedDomainName: !Sub "${EnvId}.${DomainName}"
        Port: !Ref HealthCheckPort
        ResourcePath: !Ref HealthCheckPath
        RequestInterval: !Ref RequestInterval
        FailureThreshold: !Ref FailureThreshold
        EnableSNI: true
        MeasureLatency: true
      HealthCheckTags:
        - Key: Name
          Value: !Sub "${EnvId}-api-hc"
        - Key: Env
          Value: !Ref EnvId

Outputs:
  ApiHealthCheckId:
    Description: Route 53 HealthCheck identifier for the API HTTPS check.
    Value: !Ref ApiHttpsHealthCheck
    Export:
      Name: !Sub "${EnvId}-ApiHealthCheckId"
