AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront staging distribution and continuous deployment policy


Parameters:
  EnvId:
    Type: String
    Default: distribution
    Description: Environment identifier used for cross-stack imports.
  
  EnvColor:
    Type: String
    Default: flicts
    Description: Color identifier used for cross-stack imports.

  DomainName:
    Type: String
    Description: "The domain name for the Distribution"

  LogCookies:
    Type: String
    Default: "true"

  StagingWeight:
    Type: Number
    Default: 0.00
    Description: "Traffic weight for the staging distribution (0.00 - 0.15)"

  DistributionContinuousDeploymentPolicyId:
    Type: String
    Default: ""
    Description: "The Continuous Deployment Policy Id for the Distribution"

Conditions:
  HasPolicyId: !Not [!Equals [!Ref DistributionContinuousDeploymentPolicyId, ""]] 

Resources:
  StagingDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Staging: true
        ContinuousDeploymentPolicyId: 
          Fn::If:
            - HasPolicyId
            - !Ref DistributionContinuousDeploymentPolicyId
            - !Ref "AWS::NoValue" 
        Comment: !Sub "CloudFront distribution for ${EnvId} Alias (Continuous Deployment Target)"
        Enabled: true
        DefaultRootObject: index.html
        Logging:
          Bucket: 
            Fn::Sub:
              - "${LogsBucketName}.s3.amazonaws.com"
              - LogsBucketName:
                  Fn::ImportValue: !Sub "${EnvId}-LogsBucketName"

          Prefix: !Sub "cloudfront/${EnvId}-cd-staging/"
          IncludeCookies: !Ref LogCookies
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn:
            Fn::ImportValue: !Sub "${EnvId}-AcmCertificateArn"
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3Origin
            DomainName: 
              Fn::Sub:
                - "${BucketName}.s3.${AWS::Region}.amazonaws.com"
                - BucketName:
                    Fn::ImportValue:
                      Fn::Sub: "${EnvId}-${EnvColor}-ResourcesBucketName"
            OriginAccessControlId: 
              Fn::ImportValue: !Sub "${EnvId}-OriginAccessControlId"
            S3OriginConfig: {}

          - Id: APIOrigin
            DomainName:
              Fn::ImportValue:
                Fn::Sub: "${EnvId}-ApiDnsName"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: APIOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: all

  DistributionContinuousDeploymentPolicy:
    Type: AWS::CloudFront::ContinuousDeploymentPolicy
    Properties:
      ContinuousDeploymentPolicyConfig:
        Enabled: true
        StagingDistributionDnsNames:
          - !GetAtt StagingDistribution.DomainName
        TrafficConfig:
          Type: SingleWeight
          SingleWeightConfig:
            Weight: !Ref StagingWeight
        Enabled: true

  ResourcesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Fn::ImportValue:
          Fn::Sub: "${EnvId}-${EnvColor}-ResourcesBucketName"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontServicePrincipalReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com   
            Action:
              - s3:GetObject
            Resource:
              Fn::Sub:
                - arn:aws:s3:::${BucketName}/*
                - BucketName:
                    Fn::ImportValue:
                      Fn::Sub: "${EnvId}-${EnvColor}-ResourcesBucketName"

Outputs:
  StagingDistributionId:
    Description: CloudFront distribution identifier for staging.
    Value: !Ref StagingDistribution
    Export:
      Name: !Sub "${EnvId}-StagingDistributionId"

  DistributionDomainNameStaging:
    Description: CloudFront distribution domain name for staging.
    Value: !GetAtt StagingDistribution.DomainName
    Export:
      Name: !Sub "${EnvId}-DistributionDomainName-Staging"

  ContinuousDeploymentPolicyId:
    Description: CloudFront Continuous Deployment Policy Id
    Value: !Ref DistributionContinuousDeploymentPolicy
    Export:
      Name: !Sub "${EnvId}-ContinuousDeploymentPolicyId"
