# aws cloudformation deploy --stack-name s3-distribution --template-file solutions/petoboto-resources/bucket.cform.yaml
# aws s3 cp solutions/petoboto-resources/src/ s3://$BUCKET_NAME/ --acl public-read

# aws cloudformation deploy --stack-name vpc-3ha --template-file cloudformation/vpc-3ha/template.cform.yaml
# aws cloudformation deploy --stack-name rds-mysql-sls --template-file cloudformation/rds-mysql-sls/template.cform.yaml --parameter-overrides DBPassword=Masterkey123
# mvn -f solutions/petoboto-api-fn clean verify
# sam deploy --stack-name petoboto-api-fn --template-file solutions/petoboto-api-fn/sam.cform.yaml --capabilities CAPABILITY_IAM --resolve-s3
# API_URL=$(aws cloudformation describe-stacks --stack-name petoboto-api-fn --query "Stacks[0].Outputs[?OutputKey=='PetobotoApiUrl'].OutputValue" --output text)
# echo $API_URL
# curl -s "$API_URL/api/pets/"

# aws cloudformation deploy --stack-name cloudfront --template-file cloudformation/cloudfront/template.cform.yaml
# DISTRIBUTION_DOMAIN=$(aws cloudformation describe-stacks --stack-name cloudfront --query "Stacks[0].Outputs[?OutputKey=='DistributionDomainName'].OutputValue" --output text)
# echo "http://$DISTRIBUTION_DOMAIN/"
# echo "http://$DISTRIBUTION_DOMAIN/tuna-bigfile.jpg"
# time curl -s "http://$DISTRIBUTION_DOMAIN/tuna-bigfile.jpg" -o /dev/null
# ab -k -t 333 -c 22 -r "http://$DISTRIBUTION_DOMAIN/tuna-bigfile.jpg"

AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront distribution with S3 default origin

Parameters:
  EnvId:
    Type: String
    Default: distribution
    Description: Environment identifier used for cross-stack imports.

  EnvColor:
    Type: String
    Default: blue
    Description: Color identifier used for cross-stack imports.

  DomainName:
    Type: String
    Description: "The domain name for the Distribution"

  LogCookies:
    Type: String
    Default: "true"

Resources:
  LogsBucketCD:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  OriginAccessControlCD:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${EnvId}-oac-cd"
        Description: !Sub "OAC for CloudFront distribution ${EnvId} CD"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  DistributionCD:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Staging: false
        Comment: !Sub "CloudFront distribution for ${EnvId} CD"
        Enabled: true
        PriceClass: PriceClass_100
        DefaultRootObject: index.html
        Logging:
          Bucket: !Sub "${LogsBucketCD}.s3.amazonaws.com"
          Prefix: !Sub "cloudfront/${EnvId}-cd/"
          IncludeCookies: !Ref LogCookies
        Aliases:
          - !Sub "${EnvId}-cd.${DomainName}"
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn:
            Fn::ImportValue: !Sub "${EnvId}-AcmCertificateArn"
          MinimumProtocolVersion: TLSv1.2_2021

        Origins:
          - Id: S3Origin
            DomainName: 
              Fn::Sub:
                - "${BucketName}.s3.${AWS::Region}.amazonaws.com"
                - BucketName:
                    Fn::ImportValue:
                      Fn::Sub: "${EnvId}-${EnvColor}-ResourcesBucketName"
            OriginAccessControlId: !Ref OriginAccessControlCD
            S3OriginConfig: {}

          - Id: APIOrigin
            # redirect to API Gateway endpoint http api on /api/*
            DomainName:
              Fn::ImportValue:
                Fn::Sub: "${EnvId}-PetobotoApiDnsName"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: APIOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: all


  ResourcesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Fn::ImportValue:
          Fn::Sub: "${EnvId}-${EnvColor}-ResourcesBucketName"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontServicePrincipalReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com   
            Action:
              - s3:GetObject
            Resource:
              Fn::Sub:
                - arn:aws:s3:::${BucketName}/*
                - BucketName:
                    Fn::ImportValue:
                      Fn::Sub: "${EnvId}-${EnvColor}-ResourcesBucketName"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionCD}"

  LogsBucketPolicyCD:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogsBucketCD
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontDeliveryV2PutObject
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action:
              - s3:PutObject
            Resource:
              Fn::Sub: "arn:aws:s3:::${LogsBucketCD}/cloudfront/${EnvId}-cd/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                aws:SourceAccount: !Sub "${AWS::AccountId}"
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:logs:us-east-1:${AWS::AccountId}:delivery-source/*"

Outputs:
  DistributionIdCD:
    Description: CloudFront distribution identifier for CD.
    Value: !Ref DistributionCD
    Export:
      Name: !Sub "${EnvId}-DistributionId"
      
  DistributionDomainNameCD:
    Description: CloudFront distribution domain name for CD.
    Value: !GetAtt DistributionCD.DomainName
    Export:
      Name: !Sub "${EnvId}-DistributionDomainName"
  
  LogsBucketNameCD:
    Description: S3 bucket name for CloudFront logs for CD.
    Value: !Ref LogsBucketCD
    Export:
      Name: !Sub "${EnvId}-LogsBucketName"
  
  OriginAccessControlCDId:
    Description: Origin Access Control ID for CloudFront distribution CD.
    Value: !Ref OriginAccessControlCD
    Export:
      Name: !Sub "${EnvId}-OriginAccessControlId"

