AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Petoboto API Function

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Parameters:
  EnvId:
    Type: String
    Default: project
    Description: Environment identifier used for cross-stack imports.
  
  Color:
    Type: String
    Default: flicts

Resources:
  ApiFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java21
      CodeUri: target/function.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${EnvId}-DBClientsSecurityGroupId"
        SubnetIds:
          - Fn::ImportValue: !Sub "${EnvId}-PublicSubnet1Id"
          - Fn::ImportValue: !Sub "${EnvId}-PublicSubnet2Id"
          - Fn::ImportValue: !Sub "${EnvId}-PublicSubnet3Id"
      Environment:
        Variables:
          QUARKUS_DATASOURCE_JDBC_URL:
            Fn::ImportValue: !Sub "${EnvId}-JDBCUrl"
          QUARKUS_DATASOURCE_USERNAME:
            Fn::ImportValue: !Sub "${EnvId}-DBUsername"
          QUARKUS_DATASOURCE_PASSWORD:
            Fn::ImportValue: !Sub "${EnvId}-DBPassword"
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  PetobotoApiId:
    Description: Default execute-api ID
    Value: !Ref ServerlessHttpApi
    Export:
      Name: !Sub "${EnvId}-${Color}-PetobotoApiId"

  PetobotoApiDnsName:
    Description: Default execute-api DNS Hostname
    Value: !Sub "${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${EnvId}-${Color}-PetobotoApiDnsName"

  PetobotoApiUrl:
    Description: Default execute-api URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: !Sub "${EnvId}-${Color}-PetobotoApiUrl"
    
  PetobotoApiStageName:
    Description: API stage name
    Value: "$default"
    Export:
      Name: !Sub "${EnvId}-${Color}-PetobotoApiStageName"

