Description: Alias Record

Parameters:
  EnvId:
    Type: String
    Default: project
  
  HostedZoneId:
    Type: String
    Description: "The ID of the existing Route 53 Hosted Zone"
  
  DomainName:
    Type: String
    Description: "The domain name for the ALB"

  Color:
    Type: String
    Default: flicts
    Description: Deployment color (e.g., blue/green) used to compose the alias name.

Resources:
  DistributionAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${EnvId}-${Color}.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: 
          Fn::ImportValue: !Sub "${EnvId}-${Color}-DistributionDomainName"
        HostedZoneId: Z2FDTNDATAQYW2   # CloudFront hosted zone ID (global)
        EvaluateTargetHealth: false

Outputs:
  DistributionAliasName:
    Description: Name of the CloudFront Distribution Alias Record
    Value: !Ref DistributionAliasRecord
    Export:
      Name: !Sub "${EnvId}-${Color}-DistributionAliasName"