name: AWS Janitor

on:
  workflow_dispatch: {}
  schedule:
    - cron: '33 3 * * *'

jobs:
  run-janitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Idenitity check
        run: aws sts get-caller-identity

      - name: Run janitor script
        run: ./scripts/janitor/aws-janitor.sh
