name: AWS Cleanup

on:
  # Run manually
  workflow_dispatch:
  # Run on schedule (daily at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
        
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        
    - name: Make janitor script executable
      run: chmod +x scripts/aws-janitor.sh
      
    - name: Run AWS cleanup
      run: ./scripts/aws-janitor.sh
      
    - name: Upload cleanup logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cleanup-logs-${{ github.run_number }}
        path: |
          *.log
          /tmp/*.log
        retention-days: 7